# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ReactNativeApp' do
  pod 'Firebase/Core', '~> 4.13.0'

  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  target 'ReactNativeAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
